name: Generate JIT Stencils and Create PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-stencils:
    name: Generate JIT Stencils
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    strategy:
      fail-fast: false
      matrix:
        target:
          - i686-pc-windows-msvc/msvc
          - x86_64-pc-windows-msvc/msvc
          - aarch64-pc-windows-msvc/msvc
          - x86_64-apple-darwin/clang
          - aarch64-apple-darwin/clang
          - x86_64-unknown-linux-gnu/gcc
          - aarch64-unknown-linux-gnu/gcc
        include:
          - target: i686-pc-windows-msvc/msvc
            architecture: Win32
          - target: x86_64-pc-windows-msvc/msvc
            architecture: x64
          - target: aarch64-pc-windows-msvc/msvc
            architecture: ARM64
          - target: x86_64-apple-darwin/clang
            architecture: x86_64
          - target: aarch64-apple-darwin/clang
            architecture: aarch64
          - target: x86_64-unknown-linux-gnu/gcc
            architecture: x86_64
          - target: aarch64-unknown-linux-gnu/gcc
            architecture: aarch64
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4

      - name: Clone CPython Repository
        run: git clone https://github.com/python/cpython.git

      - name: Generate Stencils for Each Target
        run: |
          echo "Generating stencils for target: ${{ matrix.target }}"
          cd cpython

          # Extract the architecture (everything before /)
          stripped_target="${{ matrix.target }}"
          stripped_target=${stripped_target%%/*}  # Remove everything after the slash

          # Configure, build, and generate stencils
          ./configure --enable-experimental-jit
          make all --jobs 4
          ./python Tools/jit/build.py $stripped_target

          # Create a target-specific directory in the outer repo
          mkdir -p ../stencils/$stripped_target

          # Move generated stencils to the external repo's stencils/ directory
          cp -r Tools/jit/output/* ../stencils/$stripped_target/

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b generate-jit-stencils
          git add stencils/
          git commit -m "Add JIT stencils for multiple architectures"
          git push origin generate-jit-stencils

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const { context, github } = require('@actions/github');
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Add JIT Stencils for all targets",
              body: "This pull request aggregates the JIT stencils generated for all architectures into a single update.\n\nGenerated automatically by the workflow.",
              head: "generate-jit-stencils",
              base: "main"
            });
            console.log(`Pull request created: ${pr.data.html_url}`);
